# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170906_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户名')),
                ('email', models.CharField(max_length=50, verbose_name='用户邮箱')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Article', verbose_name='评论所属文章')),
            ],
        ),
    ]
